import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import components
import "../components/Sidebar";
import Sidebar from "../components/Sidebar";
import RightExtra from "@/components/RightExtra";
import Navlink from "@/components/Navlink";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Orca AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-cols-[1fr_3fr_1fr] gap-4 bg-slate-50`}
      >
        <Sidebar />
        <div className="flex flex-col gap-4">
          <Navlink link="Templates / Sales Effectivness / BANT" />
          {children}
        </div>
        <RightExtra />
      </body>
    </html>
  );
}
